# 1. Port de l'interface (ce que tu tapes dans le navigateur)
server.port=8080

# 2. Dire à l'UI où se trouve Consul pour qu'elle trouve les services "user" et "patient"
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500


# 3. Configuration de Feign (On lui donne un peu de temps pour répondre)
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
