# Port de l'interface
server.port=8080

# Consul
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.hostname=host.docker.internal

# Activation de Feign (pour que Consul aide Feign à trouver les services)
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
