# CONFIGURATION MONGODB
# On utilise localhost car Mongo est dans Docker mais le code tourne dans IntelliJ
spring.data.mongodb.host=healthcare-mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=healthcare_notes

# CONFIGURATION CONSUL
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.hostname=host.docker.internal

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
