# 1. Connexion à TA base de données partagée (celle de Workbench)
# On met localhost car MySQL est dans Docker mais le code tourne dans IntelliJ
spring.datasource.url=jdbc:mysql://healthcare-mysql:3306/healthcare_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Demander à Hibernate de mettre à jour les tables si besoin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Dire au service comment trouver Consul
# On met localhost car Consul est dans Docker mais le code tourne dans IntelliJ
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500


# 4. Activer les outils de surveillance (Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
